name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Check for hustoj repository updates
        id: check-hustoj
        run: |
          COMMIT_TIMESTAMP=$(curl -s https://api.github.com/repos/zhblue/hustoj/commits/master | jq -r '.commit.committer.date')
          YESTERDAY=$(date -u -d "yesterday 00:00:00" +%s)
          COMMIT_TS=$(date -d "${COMMIT_TIMESTAMP}" +%s)
          NOW=$(date -u -d "00:00:00" +%s)
          echo "Commit timestamp: $COMMIT_TIMESTAMP"
          echo "Yesterday 16:00:00 UTC timestamp: $YESTERDAY"
          if [[ $COMMIT_TS -gt $YESTERDAY && $COMMIT_TS -le $NOW ]]; then
            echo "New commit within last 24 hours, proceeding with build."
            echo "NEED_BUILD=true" >> $GITHUB_ENV
          else
            echo "No new commit within last 24 hours, skipping build."
            echo "NEED_BUILD=false" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        if: env.NEED_BUILD == 'true' || github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: env.NEED_BUILD == 'true' || github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make build.sh executable
        if: env.NEED_BUILD == 'true' || github.event_name == 'push'
        run: chmod +x build.sh

      - name: Run build.sh
        if: env.NEED_BUILD == 'true' || github.event_name == 'push'
        run: ./build.sh

      - name: push to docker hub
        if: env.NEED_BUILD == 'true' || github.event_name == 'push'
        run: |
          DATE_TAG=$(date +%Y%m%d)
          echo "Tagging images with $DATE_TAG"
          
          docker tag yemaster/hustoj-web yemaster/hustoj-web:$DATE_TAG
          docker push yemaster/hustoj-web:latest
          docker push yemaster/hustoj-web:$DATE_TAG
          
          docker tag yemaster/hustoj-judger yemaster/hustoj-judger:$DATE_TAG
          docker push yemaster/hustoj-judger:latest
          docker push yemaster/hustoj-judger:$DATE_TAG
    
      - name: Log in to registry.abstrax.cn
        if: env.NEED_BUILD == 'true' || github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: registry.abstrax.cn
          username: ${{ secrets.ABSTRAX_USERNAME }}
          password: ${{ secrets.ABSTRAX_TOKEN }}
      
      - name: push to abstrax registry
        if: env.NEED_BUILD == 'true' || github.event_name == 'push'
        run: |
          DATE_TAG=$(date +%Y%m%d)
          echo "Tagging images with $DATE_TAG"

          docker tag yemaster/hustoj-web registry.abstrax.cn/yemaster/hustoj-web:latest
          docker tag yemaster/hustoj-web registry.abstrax.cn/yemaster/hustoj-web:$DATE_TAG
          docker push registry.abstrax.cn/yemaster/hustoj-web:latest
          docker push registry.abstrax.cn/yemaster/hustoj-web:$DATE_TAG

          docker tag yemaster/hustoj-judger registry.abstrax.cn/yemaster/hustoj-judger:latest
          docker tag yemaster/hustoj-judger registry.abstrax.cn/yemaster/hustoj-judger:$DATE_TAG
          docker push registry.abstrax.cn/yemaster/hustoj-judger:latest
          docker push registry.abstrax.cn/yemaster/hustoj-judger:$DATE_TAG